# This matches the name in the dbt_project.yml
horse_racing_dbt:
  outputs:
    dev:
      type: duckdb
      path: 'dev.duckdb' # This will create a local database file
      threads: 4
  target: dev