name: dbt_ci_pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate Mock Data
        run: |
          # Create the directory relative to the workspace root
          mkdir -p ${{ github.workspace }}/data/raw
          
          # Run the script using the absolute path to the workspace
          # We set PYTHONPATH to the workspace so imports work correctly
          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}
          python ${{ github.workspace }}/scripts/generate_mock_data.py

      - name: Run dbt
        env:
          DBT_PROFILES_DIR: ./horse_racing_dbt
        run: |
          cd horse_racing_dbt
          dbt deps
          dbt run
          dbt test